-- =====================================================
-- aiweb database initialization script
-- =====================================================
-- This script:
-- 1. Creates database and user
-- 2. Creates tables
-- 3. Creates indexes
-- 4. Initializes admin user
-- =====================================================

--------------------------------------------------------
-- 1. Database & User
--------------------------------------------------------

CREATE DATABASE aiweb;

CREATE USER aiweb_user WITH PASSWORD 'REDACTED_PASSWORD';

GRANT ALL PRIVILEGES ON DATABASE aiweb TO aiweb_user;
ALTER DATABASE aiweb OWNER TO aiweb_user;

\connect aiweb;

GRANT ALL ON SCHEMA public TO aiweb_user;
ALTER SCHEMA public OWNER TO aiweb_user;

--------------------------------------------------------
-- 2. Tables
--------------------------------------------------------

-- users
CREATE TABLE users (
    id                SERIAL PRIMARY KEY,
    username          VARCHAR NOT NULL,
    password_hash     VARCHAR NOT NULL,
    email             VARCHAR,
    phone             VARCHAR,
    role              VARCHAR,
    quota             BIGINT,
    is_active         BOOLEAN,
    is_deleted        BOOLEAN,
    avatar_url        VARCHAR,
    remark            VARCHAR,
    inviter_id        INTEGER,
    invitation_code   VARCHAR,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    last_login_at     TIMESTAMP WITHOUT TIME ZONE
);

-- plans
CREATE TABLE plans (
    id              SERIAL PRIMARY KEY,
    name            VARCHAR NOT NULL,
    description     VARCHAR,
    quota           INTEGER NOT NULL,
    duration_days   INTEGER,
    price           INTEGER DEFAULT 0,
    is_active       BOOLEAN DEFAULT true,
    created_at      TIMESTAMP WITHOUT TIME ZONE DEFAULT now()
);

-- histories
-- NOTE:
-- task_id MUST allow NULL (async generate workflow)
CREATE TABLE histories (
    id         SERIAL PRIMARY KEY,
    user_id    INTEGER,
    task_id    VARCHAR,
    prompt     VARCHAR NOT NULL,
    image_url  VARCHAR,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    status     VARCHAR DEFAULT 'pending'
);

-- quota_logs
CREATE TABLE quota_logs (
    id               SERIAL PRIMARY KEY,
    user_id          INTEGER NOT NULL,
    change           INTEGER NOT NULL,
    reason           VARCHAR NOT NULL,
    operator_id      INTEGER,
    related_plan_id  INTEGER,
    created_at       TIMESTAMP WITHOUT TIME ZONE DEFAULT now()
);

--------------------------------------------------------
-- 3. Indexes (from legacy database)
--------------------------------------------------------

-- users
CREATE UNIQUE INDEX ix_users_username ON users (username);
CREATE UNIQUE INDEX ix_users_email ON users (email);
CREATE UNIQUE INDEX ix_users_phone ON users (phone);
CREATE UNIQUE INDEX users_invitation_code_key ON users (invitation_code);
CREATE INDEX ix_users_id ON users (id);

-- histories
CREATE INDEX ix_histories_id ON histories (id);
CREATE INDEX ix_histories_task_id ON histories (task_id);

-- quota_logs
CREATE INDEX idx_quota_logs_user_id ON quota_logs (user_id);
CREATE INDEX idx_quota_logs_created_at ON quota_logs (created_at);

--------------------------------------------------------
-- 4. Initialize admin user
--------------------------------------------------------

-- IMPORTANT:
-- Replace password_hash with a REAL hash generated by argon2 or bcrypt.
-- Example (argon2):
-- $argon2id$v=19$m=65536,t=3,p=4$...

INSERT INTO users (
    username,
    password_hash,
    email,
    role,
    quota,
    is_active,
    is_deleted,
    created_at
) VALUES (
    'admin',
    '$REPLACE_WITH_REAL_PASSWORD_HASH',
    'admin@example.com',
    'admin',
    999999,
    true,
    false,
    now()
);

--------------------------------------------------------
-- 5. Final check hints (manual)
--------------------------------------------------------
-- \dt
-- SELECT id, username, role FROM users;
-- \d histories
--------------------------------------------------------

-- END OF FILE
